### ISSUE TITLE
GitHub rate limiter causing defect raising to fail

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/extensions#789]
See, for example, https://github.com/quarkusio/extensions/actions/runs/8087944319/job/22100951380

```
org.kohsuke.github.GHException: Failed to retrieve https://api.github.com/search/issues?q=is%3Aissue+is%3Aopen+%22https%3A%2F%2Fcamel.apache.org%2F_%2Fimg%2Flogo-d-f21b25ba38.svg%22+in%3Atitle+repo%3Aquarkusio%2Fextensions
	at org.kohsuke.github.GitHubPageIterator.fetch(GitHubPageIterator.java:153)
	at org.kohsuke.github.GitHubPageIterator.hasNext(GitHubPageIterator.java:89)
	at org.kohsuke.github.PagedSearchIterable$1.hasNext(PagedSearchIterable.java:86)
	at org.kohsuke.github.PagedIterator.fetch(PagedIterator.java:106)
	at org.kohsuke.github.PagedIterator.hasNext(PagedIterator.java:74)
	at org.kohsuke.github.PagedSearchIterable.populate(PagedSearchIterable.java:65)
	at org.kohsuke.github.PagedSearchIterable.getTotalCount(PagedSearchIterable.java:49)
	at Report.processBadImage(bad-image-issue.java:141)
	at Report.lambda$run$0(bad-image-issue.java:66)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at Report.run(bad-image-issue.java:66)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at Report.main(bad-image-issue.java:195)
Caused by: org.kohsuke.github.HttpException: {
  "documentation_url": "https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits",
  "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID B1E9:7941:2692D9A:4D222D1:65DFB44A."
}
	at org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:56)
```

**Comment by holly-cummins** [comment]
This may also be why we got a flurry of incorrect dead link issues raised yesterday.

**Comment by holly-cummins** [comment]
Well, we can conclude that didn't work: https://github.com/quarkusio/extensions/actions/runs/9594280664/job/26456491441
