### ISSUE TITLE
Secondary rate limit causing intermittent failure raising defects in build

### ISSUE THREAD

**Issue by holly-cummins** [quarkusio/extensions#978]
See, for example, https://github.com/quarkusio/extensions/actions/runs/8530319756

```
Found a bad image: https://camel.apache.org/_/img/logo-d-f21b25ba38.svg
org.kohsuke.github.GHException: Failed to retrieve https://api.github.com/search/issues?q=is%3Aissue+is%3Aopen+%22https%3A%2F%2Fcamel.apache.org%2F_%2Fimg%2Flogo-d-f21b25ba38.svg%22+in%3Atitle+repo%3Aquarkusio%2Fextensions
	at org.kohsuke.github.GitHubPageIterator.fetch(GitHubPageIterator.java:153)
	...
Caused by: org.kohsuke.github.HttpException: {
  "documentation_url": "https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits",
  "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID 8C80:16C8:398E628:5D4B063:660CA05C."
}
	at org.kohsuke.github.GitHubConnectorResponseErrorHandler$1.onError(GitHubConnectorResponseErrorHandler.java:56)
	at org.kohsuke.github.GitHubClient.detectKnownErrors(GitHubClient.java:424)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:386)
	at org.kohsuke.github.GitHubPageIterator.fetch(GitHubPageIterator.java:142)
	... 18 more
```

**Comment by holly-cummins** [comment]
Duplicate of #789.
